### ISSUE TITLE
Cannot get to work on IOS in Xamarin.Forms .Net Standard app

### ISSUE THREAD

**Issue by calbert52** [ThatCSharpGuy/Forms-FullCameraPage#2]
When I PushModalAsync(cameraPage), all I get is a blank white screen. This worked in the PCL version of my application, but in the ported .NET Standard it doesn't.

Any ideas?

**Comment by fferegrino** [comment]
Can you please upload a [mvce](https://stackoverflow.com/help/mcve) so that I can work on this issue. I have not made any attempt to bring this to .NET Standard but I'd really love to.

**Comment by calbert52** [comment]
Sorry about the problem post, somehow during my testing I deleted the 'CameraPageRenderer' from my iOS project. It does work in a .NET Standard project.

I have made some changes to both the iOS and Android renderer. I changed the code to use the front facing camera. In iOS, I added a override on the Dispose() method.

There is one future issue, in the Android renderer, the use of Android.Hardware.Camera is depreciated and has been replaced by 'android.hardware.camera2'. There should be a way, based on the API level to call the appropriate methods that use 'camera' or 'camera2'.

Attached are the source files containing the changes that I have made.
[CameraPageRenderer.zip](https://github.com/ThatCSharpGuy/Forms-FullCameraPage/files/2106169/CameraPageRenderer.zip)

**Comment by fferegrino** [comment]
Check https://github.com/messier16/FullCameraPage I did not apply your modifications (though the `Dispose` method may be useful) but that's working on a .NET Standard project.

Yes, the Camera2 is already an issue but I don't see myself addressing it at the moment. If you want you can create a PR on this new repository :D

On a side note, are you adding these two lines in your `Info.plist`?
https://github.com/messier16/FullCameraPage/blob/master/FullCameraApp.iOS/Info.plist#L37-L38

**Comment by calbert52** [comment]
Yes, I do have those lines in my Info.plist file since I also use the Camera for barcode scanning.

Thanks for your comments.
